.PHONY: all say_hello generate clean

all: say_hello generate

say_hello:
	@echo "HELLO World"

generate:
	@echo "Creating empty txt files..."
	touch file-{1..10}.txt

clean:
	@echo "Cleaning Up.."
	rm *.txt
